### ISSUE TITLE
Regularni izraz za tabeli nesrece1 in nesrece_udelezenci_1 v datoteki `uvoz.r`

### ISSUE THREAD

**Issue by saraconta** [saraconta/APPR-2021-22#1]
Zanima me, kako sestaviti regularni izraz za razdelitev vrstice `leto.vrsta` (oblike: leto, Prometne nesreče, niz) v tabeli `nesrece1`, saj mi izraz "^(\\d{4})\\s[A-z]+\\s[A-z]+\\s(.*)$" vse vrednosti za `leto` in `vrsta` nastavi na NA. Enako tudi pri tabeli `nesrece_udelezenci_1` (oblike: leto, Število udeležencev, niz), ko poskušam razdeliti stolpec `leto.poskodba` na stolpca `leto` in `poskodba` s pomočjo istega izraza kot prej. Koda za razdelitev je sicer enaka kodi iz predavanj.

**Comment by evadezelak** [comment]
Regularni izraz, ki si ga napisala, ne zajema šumnikov, zato ti ničesar ne najde. Torej problem je v drugi besedi (nesreče). Lahko rešiš tako: [A-zč]. Podobno pri drugi tabeli.

**Comment by evadezelak** [comment]
Opazila sem še, da imaš pri uvozu tabele pri funkciji col_types eno vejico preveč, zato koda ne deluje. To bi bilo dobro popraviti.

**Comment by saraconta** [comment]
Hvala, sedaj deluje.
