### ISSUE TITLE
Shranjevanje zemljevidov

### ISSUE THREAD

**Issue by saraconta** [saraconta/APPR-2021-22#2]
Zanima me, kako popraviti vrstico 253 v datoteki `vizualizacija.r`, da mi bo uspelo shraniti zemljevid v sliko. Koda je le prekopirana iz predavanj.

**Comment by evadezelak** [comment]
Zemljevida ne rabiš shranjevati v pdf. Shraniš si ga samo v spremenljivko in potem v datoteki Rmd pokličeš preko spremenljivke (kot smo pokazali na vajah).

**Comment by saraconta** [comment]
Hvala vam.
