### ISSUE TITLE
Metoda voditeljev

### ISSUE THREAD

**Issue by saraconta** [saraconta/APPR-2021-22#3]
Pri zadnji fazi sem pričela z metodo voditeljev v datoteki `analiza.r`. Pri pisanju kode sem se opirala na kodo iz vaj. Deluje mi vse, razen zadnja vrstica kode:
`zemljevid <- tm_shape(merge(Slovenija, skupine, by.x="NAME_1", by.y="regija")) + tm_polygons("skupina")`
Pri tem mi terminal javlja napako: 

> Error: Object merge(Slovenija, skupine, by.x = "NAME_1", by.y = "regija") is neither from class sf, stars, Spatial, Raster, nor SpatRaster.

Kljub iskanju po internetu mi ne uspe najti napake.

**Comment by evadezelak** [comment]
Problem je, da tvoj zemljevid Slovenije po regijah ni enakega tipa kot zemljevidi, ki smo jih uporabljali na vajah. Na vajah smo vedno imeli tip SpatialPolygonsDataFrame, tvoj zemljevid Slovenija pa je DataFrame, zato ne moreš uporabiti funkcij iz vaj. Vidim, da si zemljevid vzela iz predavanj, zato moraš uporabiti funkcije, ki ste jih na predavanjih uporabili za risanje zemljevida. Torej nekaj takega: 
`ggplot() +
  geom_polygon(
    data = slo.regije.poligoni,
    mapping = aes(long, lat, group = group),
    color = 'black',
    fill = 'white'
  ) +
  coord_map() +
  geom_text(
    data = slo.regije.centroidi,
    mapping = aes(x = long, y = lat, label = regija)
  )`
Seveda popraviš za svoje podatke in rabiš še centroide.

**Comment by saraconta** [comment]
Hvala za pomoč, bom poskusila.
