### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by saraconta** [saraconta/APPR-2021-22#4]
Pri poganjanju poročila mi javlja napako: `Error: object 'dendrogram' not found`. Žal ne vem, v čem je težava, saj sem pred tem pognala celoten projekt in vsa koda v povezavi z dendrogrami deluje.

**Comment by evadezelak** [comment]
Težava se pojavi že v `analiza.r`, ko naložiš datoteko `hc.kolena.r`. V tej datoteki se namreč kliče funkcija `hc.kolena(dendrogram)`, vendar pa dendrogram znotraj te datoteke ni definiran, zato ko naložiš le datoteko, javlja napako. Popraviš lahko tako, da vrstico `r = hc.kolena(dendrogram)` v datoteki `hc.kolena.r` zakomentiraš, ali pa kar izbrišeš. Potem deluje.
